apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:155830463620:certificate/6fe2ea09-b71b-4d43-9f5e-cc6294f1dcdc
  name: c1-juice-shop
  labels:
    app: c1-juice-shop
spec:
  type: LoadBalancer
  name: c1-juice-shop
  ports:
  - port: 443
    name: juice-shop
    targetPort: 3000
  selector:
    app: c1-juice-shop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: c1-juice-shop
  name: c1-juice-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c1-juice-shop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: c1-juice-shop
    spec:
      containers:
      - name: c1-juice-shop
        image: $K8S_REGISTRY/c1-juice-shop:latest
        imagePullPolicy: Always
        env:
        - name: TREND_AP_KEY
          value: $JUICE_KEY
        - name: TREND_AP_SECRET
          value: $JUICE_SECRET
        - name: TREND_AP_HELLO_URL
          value: "https://agents.de-1.application.cloudone.trendmicro.com/"
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
